version: '3.8'

services:
  frontend:
    container_name: frontend
    image: vprlol/get-science-frontend:latest
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network
    environment:
      - REACT_APP_SENTRY_DSN=${REACT_APP_SENTRY_DSN}
      - REACT_APP_SENTRY_ENV=${REACT_APP_SENTRY_ENV}
      - REACT_APP_SENTRY_RELEASE=${REACT_APP_SENTRY_RELEASE}
    volumes:
      - ./certs:/etc/nginx/certs:ro

networks:
  app-network:
    external: true
