name: Redeploy frontend

on:
  workflow_dispatch: 

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ${{ secrets.DOCKERHUB_LOGIN }}/get-science-frontend:latest

    steps:
      - name: Deploy to production server over SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DEPLOY_SSH_HOST }}
          username: ${{ secrets.DEPLOY_SSH_USER }}
          key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
          script: |
            cd /get-science/get-science-frontend
            git fetch origin
            git checkout master || git checkout -b master
            git reset --hard origin/master
            docker compose -f docker-compose.yml down
            docker rmi -f ${{ secrets.DOCKER_IMAGE_NAME }} || true
            docker pull ${{ secrets.DOCKER_IMAGE_NAME }}
            docker compose -f docker-compose.yml up -d --remove-orphans
